# version: "3.9"
services:
  azure-form-recognizer-layout:
    container_name: azure-form-recognizer-layout
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-4.0
    environment:
      - EULA=accept
      - billing=https://di-ac-ae-001.cognitiveservices.azure.com/ # $env:MNGENV_DOCINTEL_ENDPOINT_URI
      - apiKey=*** # $env:MNGENV_DOCINTEL_API_KEY
    ports:
      - "5000:5000"
    networks:
      - ocrvnet
networks:
  ocrvnet:
    driver: bridge